import { 
  Settings, Map as MapIcon, Cpu, Lightbulb, User, Leaf, Share2, BookOpen, CheckSquare,
  Search, FileText, Folder, Smartphone, Users, Heart, UserCheck, PenTool, RefreshCw, 
  Terminal, Shield, Lock, Smile, Wrench, Zap, Eye, Compass, Award, Activity, 
  Building, ArrowUpRight, GraduationCap, Layout, MessageSquare, Clipboard, 
  Monitor, HelpCircle, Target, Book, Clock, Briefcase, Globe, Star, BarChart, CheckCircle, Box, Calendar,
  MapPin, Square, Triangle, X
} from 'lucide-react';
import { HexagonIcon, CircleIcon } from './components/Icons';

export const categories = [
  { id: 'digcomp', title: 'DigComp', hex: '#f37021', color: 'bg-[#f37021]', text: 'text-[#f37021]', border: 'border-[#f37021]', gradient: 'from-[#f37021] to-[#f7941d]', icon: Cpu },
  { id: 'entrecomp', title: 'EntreComp', hex: '#91278f', color: 'bg-[#91278f]', text: 'text-[#91278f]', border: 'border-[#91278f]', gradient: 'from-[#91278f] to-[#b3519e]', icon: Lightbulb },
  { id: 'lifecomp', title: 'LifeComp', hex: '#8dc63f', color: 'bg-[#8dc63f]', text: 'text-[#8dc63f]', border: 'border-[#8dc63f]', gradient: 'from-[#8dc63f] to-[#a6ce39]', icon: User },
  { id: 'greencomp', title: 'GreenComp', hex: '#00a651', color: 'bg-[#00a651]', text: 'text-[#00a651]', border: 'border-[#00a651]', gradient: 'from-[#00a651] to-[#3cb878]', icon: Leaf },
  { id: 'transversal', title: 'Trasversali', hex: '#00aeef', color: 'bg-[#00aeef]', text: 'text-[#00aeef]', border: 'border-[#00aeef]', gradient: 'from-[#00aeef] to-[#6dcff6]', icon: Share2 },
  { id: 'setting', title: 'Setting', hex: '#6d6e71', color: 'bg-[#6d6e71]', text: 'text-[#6d6e71]', border: 'border-[#6d6e71]', gradient: 'from-[#6d6e71] to-[#939598]', icon: Settings },
  { id: 'planning', title: 'Pianificazione', hex: '#414042', color: 'bg-[#414042]', text: 'text-[#414042]', border: 'border-[#414042]', gradient: 'from-[#414042] to-[#58595b]', icon: MapIcon },
  { id: 'methods', title: 'Metodi', hex: '#3ab54a', color: 'bg-[#3ab54a]', text: 'text-[#3ab54a]', border: 'border-[#3ab54a]', gradient: 'from-[#3ab54a] to-[#8dc63f]', icon: BookOpen },
  { id: 'assessment', title: 'Valutazione', hex: '#2e3192', color: 'bg-[#2e3192]', text: 'text-[#2e3192]', border: 'border-[#2e3192]', gradient: 'from-[#2e3192] to-[#662d91]', icon: CheckSquare },
];

export const cardsData = {
  setting: [
    { code: 'SET-1', title: "OBIETTIVO", text: "Qual è l'obiettivo dell'attività?", icon: Target },
    { code: 'SET-2', title: "TEMA", text: "Quale parte del curriculum sarà oggetto dell'attività?", icon: Book },
    { code: 'SET-3', title: "DURATA", text: "Quanto durerà l'attività?", icon: Clock },
    { code: 'SET-4', title: "RISORSE", text: "Quali risorse o persone sono necessarie per l'attività?", icon: Briefcase },
    { code: 'SET-5', title: "DESTINATARI", text: "Chi saranno i/le partecipanti? Quante persone ci saranno nel gruppo?", icon: Users },
    { code: 'SET-6', title: "SPAZIO", text: "Dove si svolgerà l'attività?", icon: MapPin },
    { code: 'SET-7', title: "BISOGNI", text: "Quali bisogni degli studenti e delle studentesse saranno affrontati? Ci sono bisogni generali o specifici?", icon: Activity },
    { code: 'SET-8', title: "COLLEGAMENTI VITA REALE", text: "Quali questioni della vita reale saranno affrontate? Ci sono collegamenti con il mondo reale?", icon: Globe },
  ],
  planning: [
    { id: '1', code: 'P1', title: "SCEGLI LE COMPETENZE", text: "Su quali competenze lavoreranno i/le partecipanti? Scegli tra le carte delle competenze e posizionale qui.", icon: Star },
    { id: '2', code: 'P2', title: "DEFINISCI IL LIVELLO", text: "Quanto sono competenti i/le partecipanti? Scegli un metodo tra le carte Assessment per valutare il loro livello di partenza.", icon: BarChart },
    { id: '3', code: 'P3', title: "METODO DI INSEGNAMENTO", text: "Come insegnerai? Scegli una o più carte tra le carte Methods.", icon: GraduationCap },
    { id: '4', code: 'P4', title: "OUTPUT / EVIDENZE", text: "Che cosa vorresti che i/le partecipanti raggiungessero, facessero o producessero? Definisci quale sarà l'output finale.", icon: Award },
    { id: '5', code: 'P5', title: "METODO DI VALUTAZIONE", text: "Come valuterai i progressi dei/delle partecipanti? Scegli tra le carte di valutazione.", icon: CheckCircle },
    { id: '6', code: 'P6', title: "RACCOGLI LE RISORSE", text: "Hai tutto ciò che ti serve? Procurati le risorse necessarie e coinvolgi le persone rilevanti.", icon: Box },
    { id: '7', code: 'P7', title: "SCANSIONE TEMPORALE", text: "Come si svilupperà l'attività? Scrivi un piano e una scansione temporale dell'attività di apprendimento.", icon: Calendar },
  ],
  digcomp: [
    { code: 'd.1', title: "RICERCA DI INFORMAZIONI", transversals: ['Star', 'Square'], text: "Sviluppare strategie personali per identificare i bisogni informativi, cercare e navigare le informazioni.", hint: "Cerca in Internet informazioni su un argomento specifico.", goodWith: "e.1, g.5", icon: Search },
    { code: 'd.2', title: "VALUTARE I CONTENUTI", transversals: ['Star', 'Square'], text: "Valutare criticamente le fonti dei dati e dei contenuti digitali.", hint: "Verifica le fonti per riconoscere e smontare le fake news.", goodWith: "g.5", icon: FileText },
    { code: 'd.3', title: "GESTIRE I CONTENUTI", transversals: ['Square'], text: "Organizzare, archiviare e recuperare dati e contenuti negli ambienti digitali.", hint: "Organizza i tuoi file digitali in una struttura logica.", goodWith: "e.12", icon: Folder },
    { code: 'd.4', title: "INTERAGIRE", transversals: ['Heart', 'Cross'], text: "Usare tecnologie digitali comprendendo quali mezzi siano appropriati al contesto.", hint: "Seleziona lo strumento di comunicazione digitale adeguato.", goodWith: "e.14, g.11, l.5, l.6", icon: Smartphone },
    { code: 'd.5', title: "CONDIVIDERE", transversals: ['Heart', 'Circle'], text: "Condividere contenuti digitali fornendo i corretti riferimenti agli autori.", hint: "Condividi contenuti attribuendo il giusto credito.", goodWith: "e.14", icon: Share2 },
    { code: 'd.6', title: "CITTADINANZA DIGITALE", transversals: ['Cross', 'Circle'], text: "Usare servizi digitali per partecipare attivamente come cittadini.", hint: "Usa le tecnologie per contribuire alla tua comunità.", goodWith: "g.10, g.11, g.12", icon: Building },
    { code: 'd.7', title: "COLLABORARE", transversals: ['Circle', 'Heart'], text: "Usare strumenti collaborativi digitali per creare risorse e conoscenza.", hint: "Lavora in team a un progetto usando piattaforme cloud.", goodWith: "e.8, e.14, g.11, l.6", icon: Users },
    { code: 'd.8', title: "NETIQUETTE", transversals: ['Heart', 'Cross'], text: "Adattare le strategie comunicative ed essere consapevoli della diversità online.", hint: "Comunica online trattando le persone con rispetto.", goodWith: "l.1, l.5, l.6", icon: Heart },
    { code: 'd.9', title: "IDENTITÀ DIGITALE", transversals: ['Star', 'Square'], text: "Creare e gestire identità e tracce digitali tutelando la propria reputazione.", hint: "Gestisci i tuoi profili social per proteggere la tua immagine.", goodWith: "l.1, l.3", icon: UserCheck },
    { code: 'd.10', title: "SVILUPPARE CONTENUTI", transversals: ['Triangle', 'Square'], text: "Creare e modificare contenuti digitali in diversi formati.", hint: "Crea un prodotto digitale originale (es. video, podcast).", goodWith: "e.2", icon: PenTool },
    { code: 'd.11', title: "RIELABORARE CONTENUTI", transversals: ['Triangle', 'Hexagon'], text: "Modificare e integrare informazioni in file esistenti per creare contenuti nuovi.", hint: "Migliora un contenuto open-source esistente (es. Wikipedia).", goodWith: "e.1, e.2", icon: RefreshCw },
    { code: 'd.12', title: "COPYRIGHT E LICENZE", transversals: ['Square', 'Star'], text: "Comprendere come copyright e licenze si applicano ai contenuti digitali.", hint: "Verifica i permessi prima di utilizzare immagini prese dal web.", goodWith: "e.4", icon: FileText },
    { code: 'd.13', title: "PROGRAMMAZIONE", transversals: ['Hexagon', 'Square', 'Triangle'], text: "Sviluppare sequenze di istruzioni informatiche per risolvere un problema.", hint: "Scrivi un semplice codice o usa il coding visuale.", goodWith: "e.2, g.6, g.9", icon: Terminal },
    { code: 'd.14', title: "PROTEGGERE DISPOSITIVI", transversals: ['Hexagon', 'Square'], text: "Proteggere dispositivi e contenuti comprendendo i rischi e le misure di sicurezza.", hint: "Usa password sicure e autenticazione a due fattori.", goodWith: "e.12, l.8", icon: Shield },
    { code: 'd.15', title: "DATI PERSONALI", transversals: ['Star', 'Square'], text: "Proteggere i dati personali e la privacy negli ambienti digitali.", hint: "Analizza le impostazioni di privacy delle tue app.", goodWith: "l.3, l.8", icon: Lock },
    { code: 'd.16', title: "SALUTE E BENESSERE", transversals: ['Star'], text: "Evitare minacce al benessere fisico e psicologico durante l'uso delle tecnologie.", hint: "Stila delle regole per limitare il tempo davanti agli schermi.", goodWith: "g.3, l.3, l.8", icon: Smile },
    { code: 'd.17', title: "AMBIENTE E DIGITALE", transversals: ['Star', 'Square'], text: "Essere consapevoli dell'impatto ambientale dei dispositivi digitali e del loro uso.", hint: "Calcola l'impatto ambientale del ciclo di vita del tuo smartphone.", goodWith: "g.3", icon: Leaf },
    { code: 'd.18', title: "PROBLEMI TECNICI", transversals: ['Hexagon', 'Square'], text: "Identificare problemi tecnici nei dispositivi digitali e risolverli.", hint: "Crea una mini-guida per risolvere i problemi informatici più comuni.", goodWith: "g.6", icon: Wrench },
    { code: 'd.19', title: "BISOGNI E RISPOSTE", transversals: ['Hexagon', 'Triangle'], text: "Personalizzare strumenti digitali per rispondere ai bisogni e promuovere l'accessibilità.", hint: "Trova un'app che aiuti persone con specifiche disabilità.", goodWith: "e.1, e.2, g.6, g.9", icon: Zap },
    { code: 'd.20', title: "USARE CREATIVAMENTE", transversals: ['Triangle', 'Hexagon'], text: "Usare le tecnologie digitali per creare conoscenza e processi innovativi.", hint: "Risolvi un problema pratico usando uno strumento digitale in modo inatteso.", goodWith: "e.1, e.2, g.6, g.9", icon: Lightbulb },
    { code: 'd.21', title: "LACUNE NELLE COMPETENZE", transversals: ['Star', 'Hexagon'], text: "Comprendere e migliorare la propria competenza digitale e sostenere gli altri.", hint: "Autovaluta le tue competenze digitali e crea un piano di studio.", goodWith: "e.6, e.15, l.9", icon: BarChart },
  ],
  entrecomp: [
    { code: 'e.1', title: "INDIVIDUARE OPPORTUNITÀ", transversals: ['Star', 'Hexagon'], text: "Analizzare il contesto sociale per individuare sfide e cogliere opportunità per creare valore.", hint: "Individua un problema nel tuo quartiere e proponi un'idea per risolverlo.", goodWith: "d.1, d.11, d.19, d.20, g.4, g.5, g.6, g.10, l.8", icon: Eye },
    { code: 'e.2', title: "CREATIVITÀ", transversals: ['Triangle', 'Hexagon'], text: "Sviluppare idee creative e intenzionali per generare effetti di valore.", hint: "Trova 50 modi diversi e creativi per usare una semplice matita.", goodWith: "d.10, d.11, d.13, d.19, d.20, g.4, g.5, g.6, g.9", icon: Zap },
    { code: 'e.3', title: "VISIONE", transversals: ['Triangle', 'Star'], text: "Immaginare il futuro per orientare gli sforzi e trasformare le idee in azione.", hint: "Progetta una 'vision board' su come sarà il tuo settore tra 20 anni.", goodWith: "l.2, g.7, g.9, g.10", icon: Compass },
    { code: 'e.4', title: "VALORIZZARE LE IDEE", transversals: ['Square', 'Star'], text: "Riconoscere il valore sociale ed economico delle idee e come condividerlo.", hint: "Fai un'analisi SWOT (Punti di forza/debolezza) di un'idea di progetto.", goodWith: "d.12, g.5", icon: Award },
    { code: 'e.5', title: "PENSIERO ETICO", transversals: ['Star', 'Cross'], text: "Comportarsi in modo etico valutando l'impatto delle proprie azioni.", hint: "Confronta tre modi diversi di viaggiare e valutane etica e sostenibilità.", goodWith: "g.1, g.2, g.3, g.4, l.3", icon: Leaf },
    { code: 'e.6', title: "CONSAPEVOLEZZA DI SÉ", transversals: ['Star'], text: "Identificare punti di forza e debolezza per costruire fiducia in se stessi.", hint: "Crea una mappa delle tue competenze attuali e dei tuoi obiettivi futuri.", goodWith: "d.21, g.12, l.1, l.7", icon: UserCheck },
    { code: 'e.7', title: "MOTIVAZIONE", transversals: ['Hexagon'], text: "Essere resilienti, focalizzati e determinati, non arrendendosi alle avversità.", hint: "Identifica cosa ti demotiva e scrivi 3 strategie per superarlo.", goodWith: "l.1, l.7", icon: Activity },
    { code: 'e.8', title: "MOBILITARE RISORSE", transversals: ['Hexagon', 'Circle'], text: "Ottenere supporto e gestire risorse materiali e immateriali efficacemente.", hint: "Elenca le risorse necessarie per un evento e assegna le responsabilità.", goodWith: "d.7", icon: Box },
    { code: 'e.9', title: "ALFABETIZZAZIONE ECONOMICA", transversals: ['Square'], text: "Comprendere concetti finanziari per definire un budget e creare valore.", hint: "Stila il budget preventivo per realizzare un piccolo progetto scolastico.", goodWith: "g.1, g.2, g.3, l.3", icon: Building },
    { code: 'e.10', title: "MOBILITARE GLI ALTRI", transversals: ['Heart', 'Circle'], text: "Ispirare e persuadere gli stakeholder rilevanti per ottenere supporto.", hint: "Prepara un 'elevator pitch' di 1 minuto per convincere un investitore.", goodWith: "l.5, g.11, g.10", icon: Share2 },
    { code: 'e.11', title: "PRENDERE L'INIZIATIVA", transversals: ['Hexagon', 'Circle'], text: "Lavorare in modo autonomo, agire per raggiungere obiettivi e mantenere le intenzioni.", hint: "Identifica il primo passo pratico verso un obiettivo e compilo subito.", goodWith: "g.10, g.11, g.12", icon: ArrowUpRight },
    { code: 'e.12', title: "PIANIFICAZIONE E GESTIONE", transversals: ['Square', 'Hexagon'], text: "Definire priorità e piani d'action per raggiungere obiettivi adattandosi agli imprevisti.", hint: "Crea un diagramma di Gantt per gestire i tempi del tuo prossimo progetto.", goodWith: "d.3, d.14, g.7, g.8, l.2", icon: MapIcon },
    { code: 'e.13', title: "GESTIRE INCERTEZZA E RISCHIO", transversals: ['Hexagon', 'Star'], text: "Calcolare i rischi legati alle decisioni ed essere pronti a cambiare i piani.", hint: "Immagina che il tuo progetto fallisca: scrivi un 'Piano B' di emergenza.", goodWith: "g.8, l.2", icon: RefreshCw },
    { code: 'e.14', title: "LAVORARE CON GLI ALTRI", transversals: ['Circle', 'Heart'], text: "Cooperare con gli altri per sviluppare idee e trasformarle in azione.", hint: "Lavora in gruppo dividendo equamente i compiti in base alle attitudini.", goodWith: "d.4, d.5, d.7, g.11, l.4, l.6", icon: Users },
    { code: 'e.15', title: "IMPARARE DALL'ESPERIENZA", transversals: ['Star', 'Square'], text: "Riflettere su successi e fallimenti per valorizzare l'esperienza e imparare con i pari.", hint: "Dopo un'attività, scrivi 2 cose andate bene e 1 da migliorare.", goodWith: "l.7, l.8, l.9, d.21", icon: GraduationCap },
  ],
  lifecomp: [
    { code: 'l.1', title: "AUTOREGOLAZIONE", transversals: ['Star'], text: "Sviluppare consapevolezza e gestione di emozioni, pensieri e comportamenti.", hint: "Pratica tecniche di respirazione per gestire lo stress prima di un compito.", goodWith: "d.8, d.9, e.6, e.7, g.1, g.10, g.12", icon: UserCheck },
    { code: 'l.2', title: "FLESSIBILITÀ", transversals: ['Hexagon', 'Star'], text: "Gestire transizioni e incertezza e affrontare le sfide con prontezza.", hint: "Prova a svolgere una tua routine quotidiana in un modo completamente nuovo.", goodWith: "e.3, e.12, e.13, g.8", icon: RefreshCw },
    { code: 'l.3', title: "BENESSERE", transversals: ['Heart'], text: "Prendersi cura della salute fisica, mentale e sociale per perseguire la soddisfazione.", hint: "Scrivi un decalogo delle buone abitudini per il benessere della tua classe.", goodWith: "d.9, d.15, d.16, e.5, e.9, g.1, g.3", icon: Heart },
    { code: 'l.4', title: "EMPATIA", transversals: ['Heart', 'Cross'], text: "Comprendere e rispondere alle emozioni, esperienze e valori degli altri.", hint: "Ascolta attivamente un compagno per 5 minuti senza interromperlo.", goodWith: "e.14, g.1, g.2, g.3", icon: Smile },
    { code: 'l.5', title: "COMUNICAZIONE", transversals: ['Heart'], text: "Usare strategie comunicative specifiche in base al contesto e al pubblico.", hint: "Spiega un concetto complesso usando solo parole semplici e metafore.", goodWith: "d.4, d.8, e.10", icon: MessageSquare },
    { code: 'l.6', title: "COLLABORAZIONE", transversals: ['Circle', 'Heart'], text: "Partecipare ad attività di gruppo nel rispetto delle idee degli altri.", hint: "Create insieme un 'Contratto di Team' con le regole per collaborare bene.", goodWith: "d.4, d.7, d.8, e.14, g.11", icon: Users },
    { code: 'l.7', title: "MENTALITÀ DI CRESCITA", transversals: ['Star', 'Hexagon'], text: "Credere nel potenziale di miglioramento proprio e altrui (Growth Mindset).", hint: "Quando sbagli, invece di dire 'Non ci riesco', aggiungi la parola 'ANCORA'.", goodWith: "e.6, e.7, e.15", icon: Activity },
    { code: 'l.8', title: "PENSIERO CRITICO", transversals: ['Star', 'Square'], text: "Valutare le informazioni per sviluppare conclusioni ragionate e soluzioni.", hint: "Organizza un dibattito su un tema in cui devi difendere l'opinione opposta alla tua.", goodWith: "d.14, d.15, d.16, e.1, e.15, g.4, g.5, g.6", icon: Lightbulb },
    { code: 'l.9', title: "GESTIRE L'APPRENDIMENTO", transversals: ['Square', 'Star'], text: "Pianificare, organizzare e monitorare il proprio percorso di apprendimento.", hint: "Compila un diario di bordo giornaliero per riflettere su cosa hai imparato oggi.", goodWith: "d.21, e.15", icon: BookOpen },
  ],
  greencomp: [
    { code: 'g.1', title: "VALORIZZARE LA SOSTENIBILITÀ", transversals: ['Star', 'Cross'], text: "Riflettere sui valori personali e allinearli alla sostenibilità ambientale e sociale.", hint: "Discuti in classe l'importanza di mettere il pianeta prima del profitto.", goodWith: "e.5, e.9, l.1, l.3, l.4", icon: Heart },
    { code: 'g.2', title: "SOSTENERE L'EQUITÀ", transversals: ['Cross', 'Heart'], text: "Sostenere giustizia ed equità per le generazioni presenti e future.", hint: "Ricerca un caso di ingiustizia climatica nel mondo e proponi una soluzione.", goodWith: "e.5, e.9, l.4", icon: Briefcase },
    { code: 'g.3', title: "PROMUOVERE LA NATURA", transversals: ['Heart', 'Cross'], text: "Rispettare i diritti delle altre specie per tutelare e rigenerare gli ecosistemi.", hint: "Documentati sulla perdita di biodiversità causata dagli allevamenti intensivi.", goodWith: "d.16, d.17, e.5, e.9, l.3, l.4", icon: Leaf },
    { code: 'g.4', title: "PENSIERO SISTEMICO", transversals: ['Square', 'Hexagon'], text: "Affrontare un problema ambientale considerando tutte le interazioni del sistema globale.", hint: "Traccia su una mappa l'intero ciclo di produzione, trasporto e smaltimento di una T-shirt.", goodWith: "e.1, e.2, e.5, l.8", icon: Share2 },
    { code: 'g.5', title: "PENSIERO CRITICO AMBIENTALE", transversals: ['Star', 'Square'], text: "Valutare le informazioni in ottica ecologica per sviluppare soluzioni innovative.", hint: "Analizza criticamente un caso di 'Greenwashing' da parte di una grande azienda.", goodWith: "l.8, d.1, d.2, e.1, e.2, e.4", icon: Lightbulb },
    { code: 'g.6', title: "INQUADRAMENTO DEL PROBLEMA", transversals: ['Hexagon', 'Square'], text: "Riformulare le sfide quotidiane come veri e propri problemi di sostenibilità.", hint: "Ridisegna il 'percorso utente' della mensa scolastica per azzerare gli sprechi alimentari.", goodWith: "d.13, d.18, d.19, d.20, e.1, e.2, l.8", icon: Layout },
    { code: 'g.7', title: "ALFABETIZZAZIONE AI FUTURI", transversals: ['Triangle', 'Star'], text: "Immaginare futuri sostenibili alternativi e identificare i passi per realizzarli.", hint: "Scrivi un racconto ambientato nel 2050 in cui l'umanità ha risolto la crisi climatica.", goodWith: "e.3, e.12", icon: Eye },
    { code: 'g.8', title: "ADATTABILITÀ", transversals: ['Hexagon', 'Star'], text: "Gestire le transizioni ecologiche in situazioni di incertezza e ambiguità.", hint: "Simula l'impatto di un blackout energetico di 3 giorni e pianifica come adattarsi.", goodWith: "e.12, e.13, l.2", icon: RefreshCw },
    { code: 'g.9', title: "PENSIERO ESPLORATIVO", transversals: ['Triangle', 'Hexagon'], text: "Collegare discipline diverse usando creatività per l'innovazione sostenibile.", hint: "Inventa un nuovo materiale biodegradabile unendo concetti di biologia e design.", goodWith: "d.13, d.19, d.20, e.2, e.3", icon: Activity },
    { code: 'g.10', title: "AZIONE POLITICA", transversals: ['Heart', 'Circle'], text: "Chiedere politiche efficaci per la sostenibilità e individuare le responsabilità.", hint: "Scrivi una lettera formale al Sindaco per proporre un miglioramento ecologico in città.", goodWith: "d.6, e.1, e.3, e.10, e.11, l.1", icon: Building },
    { code: 'g.11', title: "AZIONE COLLETTIVA", transversals: ['Circle', 'Heart'], text: "Agire per il cambiamento sistemico in collaborazione e sinergia con gli altri.", hint: "Organizza una campagna di sensibilizzazione ambientale all'interno della scuola.", goodWith: "d.4, d.6, d.7, e.10, e.11, e.14, l.6", icon: Users },
    { code: 'g.12', title: "INIZIATIVA INDIVIDUALE", text: "Individuare il proprio potenziale per la sostenibilità e contribuire attivamente.", transversals: ['Hexagon', 'Star'], hint: "Scegli un'abitudine inquinante che hai e sostituiscila con una sostenibile per 21 giorni.", goodWith: "d.6, e.6, e.11, l.1", icon: UserCheck },
  ],
  transversal: [
    { code: 'TR-1', title: "PENSIERO CRITICO", text: "Concettualizzare, analizzare, sintetizzare e valutare informazioni per sviluppare conclusioni o agire.", icon: Star },
    { code: 'TR-2', title: "RISOLUZIONE DEI PROBLEMI", text: "Pensare, comprendere e affrontare situazioni complesse quando non esiste una soluzione immediata.", icon: HexagonIcon },
    { code: 'TR-3', title: "LAVORO DI SQUADRA", text: "Operare e comunicare in modo fluido ed efficace all'interno di un gruppo per raggiungere obiettivi comuni.", icon: CircleIcon },
    { code: 'TR-4', title: "COMUNICAZIONE E NEGOZIAZIONE", text: "Comunicare informazioni e idee in modo efficace a pubblici diversi e stabilire un dialogo risolutivo.", icon: Heart },
    { code: 'TR-5', title: "COMPETENZE ANALITICHE", text: "Suddividere informazioni e dati in componenti più semplici e gestibili per trarre conclusioni.", icon: Square },
    { code: 'TR-6', title: "CREATIVITÀ", text: "Sviluppare idee creative e intenzionali per generare effetti di grande valore.", icon: Triangle },
    { code: 'TR-7', title: "COMPETENZE INTERCULTURALI", text: "Interagire in modo efficace e appropriato in situazioni interculturali molto diverse tra loro.", icon: X },
  ],
  methods: [
    { code: 'M-1', title: "PROJECT-BASED LEARNING", text: "Apprendimento basato su progetti e sfide reali.", steps: ["1. Identifica problema", "2. Indagine", "3. Genera idee", "4. Crea prodotto", "5. Riflessione finale"], icon: Layout },
    { code: 'M-2', title: "LEARNER-LED LEARNING", text: "I/le partecipanti guidano in autonomia il proprio apprendimento.", steps: ["1. Scegli il tema", "2. Identifica metodi", "3. Definisci obiettivi", "4. Applica competenze", "5. Trasferisci altrove"], icon: User },
    { code: 'M-3', title: "CREAZIONE DI VALORE", text: "Creare qualcosa di valore per uno stakeholder esterno.", steps: ["1. Pensa ai beneficiari", "2. Trova opportunità", "3. Agisci per creare valore", "4. Usa i feedback", "5. Valuta l'impatto"], icon: Compass },
    { code: 'M-4', title: "APPRENDIMENTO COOPERATIVO", text: "Imparare in gruppo, supportandosi a vicenda per un fine comune.", steps: ["1. Lavoro in team", "2. Obiettivi interdipendenti", "3. Co-creazione", "4. Criteri condivisi", "5. Insegnamento reciproco"], icon: Users },
    { code: 'M-5', title: "SERIAMENTE LUDICO", text: "Atteggiamento esplorativo stimolato dalle meccaniche del gioco.", steps: ["1. Impara dall'errore", "2. Attività di gioco", "3. Scopo formativo", "4. Emozioni in gioco", "5. Problem-solving ludico"], icon: Activity },
    { code: 'M-6', title: "APPRENDIMENTO LABORATORIALE", text: "Sperimentazione pratica e iterativa (hands-on).", steps: ["1. Sperimenta materiali", "2. Impara facendo", "3. Gestisci fallimenti", "4. Documenta i passaggi", "5. Rifletti sui dati"], icon: Activity },
    { code: 'M-7', title: "SERVICE LEARNING", text: "Trasformare idee in azioni concrete per i bisogni della comunità.", steps: ["1. Contatta la comunità", "2. Esplora il valore civico", "3. Attivati per il bene comune", "4. Chiedi feedback", "5. Celebra i risultati"], icon: Heart },
  ],
  assessment: [
    { code: 'A-1', title: "FEEDBACK TRA PARI", text: "I/le partecipanti danno e ricevono feedback costruttivi dai colleghi.", hint: "Insegna ai ragazzi la tecnica del 'Feedback a panino' (Positivo-Miglioramento-Positivo).", icon: MessageSquare },
    { code: 'A-2', title: "AUTORIFLESSIONE", text: "Riflettere sul proprio lavoro per autovalutarsi rispetto ai criteri stabiliti.", hint: "Fai compilare una rubrica di autovalutazione alla fine di ogni fase importante.", icon: Eye },
    { code: 'A-3', title: "EVIDENZE VALUTATIVE", text: "Usare vari media (foto, video, testi) per documentare le competenze acquisite.", hint: "Chiedi agli studenti di creare un portfolio digitale dei loro lavori migliori.", icon: Clipboard },
    { code: 'A-4', title: "VALUTAZIONE AUTENTICA", text: "Valutare applicando ciò che si è imparato in contesti del mondo reale.", hint: "Organizza una simulazione in cui gli studenti presentano il progetto a veri esperti.", icon: Building },
    { code: 'A-5', title: "VALUTAZIONE DIGITALE", text: "Quiz e valutazioni digitali che offrono reportistica e feedback immediato.", hint: "Usa strumenti come Kahoot o moduli interattivi per un check rapido delle conoscenze.", icon: Monitor },
    { code: 'A-6', title: "OSSERVAZIONE", text: "Monitorare progressi, dinamiche di gruppo e competenze direttamente in azione.", hint: "Gira per i tavoli con una griglia di osservazione per segnare le competenze trasversali emerse.", icon: Eye },
    { code: 'A-7', title: "DOMANDE PER APPRENDERE", text: "Porre domande stimolanti per spingere i partecipanti ad esplorare e affinare il pensiero.", hint: "Invece di dare risposte, rispondi con domande del tipo: 'E cosa succederebbe se...?'", icon: HelpCircle },
  ]
};

export const processSteps = [
  { id: 1, title: "1. Contesto", instruction: "Seleziona le carte Setting per definire il quadro generale dell'intervento.", categories: ['setting'] },
  { id: 2, title: "2. Planning", instruction: "Disponi le carte Planning (1-7) per strutturare in sequenza la tua attività.", categories: ['planning'] },
  { id: 3, title: "3. Competenze", instruction: "Scegli le competenze europee da sviluppare. Usa i filtri per navigare tra i framework.", categories: ['digcomp', 'entrecomp', 'lifecomp', 'greencomp', 'transversal'] },
  { id: 4, title: "4. Livello", instruction: "Usa la carta P2 con un metodo Assessment per preparare la diagnosi del livello iniziale.", categories: ['planning', 'assessment'], filter: (c) => c.id === '2' || c.code?.startsWith('A') },
  { id: 5, title: "5. Metodo", instruction: "Seleziona l'approccio pedagogico più adatto dalla libreria Metodi.", categories: ['methods'] },
  { id: 6, title: "6. Output", instruction: "Definisci con la carta P4 il prodotto finale tangibile dell'apprendimento.", categories: ['planning'], filter: (c) => c.id === '4' },
  { id: 7, title: "7. Valutazione", instruction: "Pianifica la valutazione dei progressi in itinere (Assessment) durante l'attività.", categories: ['assessment'] },
  { id: 8, title: "8. Risorse", instruction: "Crea con la carta P6 la checklist organizzativa dei materiali e persone.", categories: ['planning'], filter: (c) => c.id === '6' },
  { id: 9, title: "9. Timeline", instruction: "Stendi il programma cronologico definitivo sotto la carta P7.", categories: ['planning'], filter: (c) => c.id === '7' },
];
